services:
  gateway:
    image: nginx:stable-alpine
    container_name: secops-gateway
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/ssl/cloudflare/origin.crt:/etc/ssl/cloudflare/origin.crt:ro
      - /etc/ssl/cloudflare/origin.key:/etc/ssl/cloudflare/origin.key:ro
    depends_on:
      - frontend
      - ctfd-nginx
      - jenkins
    networks:
      - secops-net

  frontend:
    build:
      context: ./frontend
    container_name: secops-frontend
    restart: unless-stopped
    networks:
      - secops-net

  ctfd:
    build:
      context: ./CTFd
    container_name: secops-ctfd
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql+pymysql://ctfd:${DB_PASSWORD}@db/ctfd
      - REDIS_URL=redis://cache:6379
      - SECRET_KEY=${CTFD_SECRET_KEY}
      - REVERSE_PROXY=true
    depends_on:
      - db
      - cache
    networks:
      - secops-net
      - internal

  ctfd-nginx:
    image: nginx:stable
    container_name: secops-ctfd-nginx
    restart: unless-stopped
    volumes:
      - ./CTFd/conf/nginx/http.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ctfd
    networks:
      - secops-net

  db:
    image: mariadb:10.11
    container_name: secops-db
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_USER=ctfd
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=ctfd
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - internal

  cache:
    image: redis:7
    container_name: secops-redis
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks:
      - internal

  jenkins:
    build:
      context: ./jenkins-docker
    container_name: jenkins
    user: root
    restart: unless-stopped
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
      - JAVA_OPTS=-Xms256m -Xmx768m
    ports:
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/cloud_projet:/workspace/cloud_projet
    networks:
      - secops-net

networks:
  secops-net:
  internal:
    internal: true

volumes:
  dbdata:
  redisdata:
  jenkins_home:
