server {
    listen 80;
    server_name _;

    location / {
        root /usr/share/nginx/html/webroot;
        index index.html;
    }

    location /.well-known/acme-challenge/ {
        root /usr/share/nginx/html/webroot;
    }
}
