events {
    worker_connections 1024;
}

http {
    include mime.types;

    client_max_body_size 50M;
    server_tokens off;

    # 🔒 Security Headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

    # =========================
    # HTTP → HTTPS REDIRECT
    # =========================
    server {
        listen 80;
        server_name project-cloud.online www.project-cloud.online ctf.project-cloud.online jenkins.project-cloud.online;

        # Certbot challenge
        location /.well-known/acme-challenge/ {
            root /usr/share/nginx/html/webroot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    # =========================
    # FRONTEND
    # =========================
    server {
        listen 443 ssl http2;
        server_name project-cloud.online www.project-cloud.online;

        ssl_certificate /etc/letsencrypt/live/project-cloud.online/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/project-cloud.online/privkey.pem;

        location / {
            proxy_pass http://frontend:80;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    # =========================
    # CTFd
    # =========================
    server {
        listen 443 ssl http2;
        server_name ctf.project-cloud.online;

        ssl_certificate /etc/letsencrypt/live/project-cloud.online/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/project-cloud.online/privkey.pem;

        location / {
            proxy_pass http://ctfd-nginx:80;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto https;
        }
    }

    # =========================
    # JENKINS
    # =========================
    server {
        listen 443 ssl http2;
        server_name jenkins.project-cloud.online;

        ssl_certificate /etc/letsencrypt/live/project-cloud.online/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/project-cloud.online/privkey.pem;

        location / {
            proxy_pass http://jenkins:8080;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto https;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
