[agent]
  interval = "5s"
  round_interval = true
  flush_interval = "5s"
  flush_jitter = "0s"
  collection_jitter = "0s"
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  omit_hostname = true

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  timeout = "5s"
  gather_services = false

[[outputs.prometheus_client]]
  listen = ":9273"
  path = "/metrics"
  expiration_interval = "60s"
